"""
Django settings for jDREAM project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4@5%xe9_nr7)!(m14ee07eg9b+kh_ukt5hz-hldi&pe^dh9ytk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oauth2_provider',
    'corsheaders',
    'rest_framework',
    'social_django',
    'dreamjub',
    'login',
    'portal'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'dreamjub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dreamjub.wsgi.application'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# Custom login backend
AUTHENTICATION_BACKENDS = [
    'oauth2_provider.backends.OAuth2Backend',
    'social_core.backends.saml.SAMLAuth',
    'login.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend'
]

LOGIN_URL = "/login/saml/login/saml/?idp=jacobs"


# Add CORS middleware
MIDDLEWARE_CLASSES += (
    'corsheaders.middleware.CorsMiddleware',
)
CORS_ORIGIN_ALLOW_ALL = True


# OAuth scope settings
OAUTH2_PROVIDER = {
    'SCOPES': {
        'profile': 'Read your user profile',
        'courses': 'Read courses you are participating in',
        'edit': 'Make changes to your profile'
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100
}


# Django media settings
MEDIA_ROOT = "media_files"
MEDIA_URL = "http://localhost:8080/"  # Serve this separately (Mongoose maybe)


# SAML upstream auth settings
SOCIAL_AUTH_SAML_SP_ENTITY_ID = 'http://saml.jacobs.university'
SOCIAL_AUTH_SAML_SP_PUBLIC_CERT = """
MIIC7DCCAlWgAwIBAgIJAPFlSmDbIDuxMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYD
VQQGEwJERTEPMA0GA1UECAwGQnJlbWVuMQ8wDQYDVQQHDAZCcmVtZW4xGTAXBgNV
BAoMEFVTRyBXZWIgU2VydmljZXMxGjAYBgNVBAMMEWphY29icy51bml2ZXJzaXR5
MSYwJAYJKoZIhvcNAQkBFhdhZG1pbkBqYWNvYnMudW5pdmVyc2l0eTAeFw0xNzA5
MTIwNDUzNDRaFw0yNzA5MTIwNDUzNDRaMIGOMQswCQYDVQQGEwJERTEPMA0GA1UE
CAwGQnJlbWVuMQ8wDQYDVQQHDAZCcmVtZW4xGTAXBgNVBAoMEFVTRyBXZWIgU2Vy
dmljZXMxGjAYBgNVBAMMEWphY29icy51bml2ZXJzaXR5MSYwJAYJKoZIhvcNAQkB
FhdhZG1pbkBqYWNvYnMudW5pdmVyc2l0eTCBnzANBgkqhkiG9w0BAQEFAAOBjQAw
gYkCgYEAr439Hn6JySjtBHQhPnFYPrIL+8xd+53uDM1ft7uc757huLK3IXRLXMil
qNgfXMGXv5DIW3KTcZMjwKV6z0NzqaPb2PbGnkTTIsLSS28HfRimM9bzhmmVRIEG
Ws7mmD+hKG1MuKmG86hXL66c2RAsFncQ/2edW2DQA2b4lTe95JUCAwEAAaNQME4w
HQYDVR0OBBYEFEfIxGvICdzuGefWGGv57CXvaGMQMB8GA1UdIwQYMBaAFEfIxGvI
CdzuGefWGGv57CXvaGMQMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADgYEA
cOEh47ehAeSVGzeOUWbRb1L5gfMOEUVPELnW5KQCfiE7niBq2VYvXTxHpWxFzXXL
c0GlmDZHZA1v5e3bxmkGrcrGkrL2+UBTK7PfT/GtEb4QT4ITadxb0ru5E84RwNpD
VceAtQ+ruREfmcpbVEfUXPimvkLK8CVip26i7CbOwwY="""

SOCIAL_AUTH_SAML_SP_PRIVATE_KEY = """
MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAK+N/R5+icko7QR0
IT5xWD6yC/vMXfud7gzNX7e7nO+e4biytyF0S1zIpajYH1zBl7+QyFtyk3GTI8Cl
es9Dc6mj29j2xp5E0yLC0ktvB30YpjPW84ZplUSBBlrO5pg/oShtTLiphvOoVy+u
nNkQLBZ3EP9nnVtg0ANm+JU3veSVAgMBAAECgYEAihGa7FvK0/mrB2CqMKkGJTD0
udFObTEVYt43FJKqZ87GafOskdQb3Vo056kqaVIcnd4ppbpj+eQmL0I2Z0H+eTLe
6rVFZivCqgdXoqUGiE4tNJw8c/fzP/HLfY+vF+sJnTw+3XskLdoNZ1rpk/vKmOzz
yedCPzs+TgfkV3dm8TUCQQDpFEw0p93McNSc9gmJ0Gyb0IkRIT+BiMZgAcPCj5vI
TIYOEDkcyCjD/gL0/4Egjz5eFYvi3azL3eqw6q1irS37AkEAwNGGbgNWmUT/ZoEG
DtSWZFxs5SLkElCHBi99qE07yAR0fXacPNFDiuV1N8PNJ2Qe3FwavjfPS5MU6R7P
gGaCrwJBAJg0nhMgsBGqeN1LOi1aAyK5Slj6WktPsyPM4zZxq2xgtIYIiBNIjn52
qR2uoHdPs42jCmeLFSVIdNM1XSZ8KvMCQH9fqhswj1tujf0LzJGtc6/WsoTneJx0
n83BP5QXeR9XehCLcwhmAOVXUQjGitazuAM/wNbZjVHSVqTtGowqq7cCQC4yAH+J
vGHMf9jKKJrG96HdeGs8UVVrqBlCQ07C1Tq5b56C2mcvPH90TnuCQ0YHXe3wq1cD
7xBPnPMrzWuxKTc="""

SOCIAL_AUTH_SAML_ORG_INFO = {
    "en-US": {
        "name": "student-run-services",
        "displayname": "Student-run web services",
        "url": "http://jacobs.university",
    }
}

SOCIAL_AUTH_SAML_TECHNICAL_CONTACT = {
    "givenName": "Leonhard Kuboschek",
    "emailAddress": "leonhard@kuboschek.me"
}

SOCIAL_AUTH_SAML_SUPPORT_CONTACT = {
    "givenName": "Leonhard Kuboschek",
    "emailAddress": "leonhard@kuboschek.me"
}

SOCIAL_AUTH_SAML_ENABLED_IDPS = {
    "testshib": {
        "entity_id": "https://idp.testshib.org/idp/shibboleth",
        "url": "https://idp.testshib.org/idp/profile/SAML2/Redirect/SSO",
        "x509cert": "MIIDAzCCAeugAwIBAgIVAPX0G6LuoXnKS0Muei006mVSBXbvMA0GCSqGSIb3DQEB CwUAMBsxGTAXBgNVBAMMEGlkcC50ZXN0c2hpYi5vcmcwHhcNMTYwODIzMjEyMDU0 WhcNMzYwODIzMjEyMDU0WjAbMRkwFwYDVQQDDBBpZHAudGVzdHNoaWIub3JnMIIB IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg9C4J2DiRTEhJAWzPt1S3ryh m3M2P3hPpwJwvt2q948vdTUxhhvNMuc3M3S4WNh6JYBs53R+YmjqJAII4ShMGNEm lGnSVfHorex7IxikpuDPKV3SNf28mCAZbQrX+hWA+ann/uifVzqXktOjs6DdzdBn xoVhniXgC8WCJwKcx6JO/hHsH1rG/0DSDeZFpTTcZHj4S9MlLNUtt5JxRzV/MmmB 3ObaX0CMqsSWUOQeE4nylSlp5RWHCnx70cs9kwz5WrflnbnzCeHU2sdbNotBEeTH ot6a2cj/pXlRJIgPsrL/4VSicPZcGYMJMPoLTJ8mdy6mpR6nbCmP7dVbCIm/DQID AQABoz4wPDAdBgNVHQ4EFgQUUfaDa2mPi24x09yWp1OFXmZ2GPswGwYDVR0RBBQw EoIQaWRwLnRlc3RzaGliLm9yZzANBgkqhkiG9w0BAQsFAAOCAQEASKKgqTxhqBzR OZ1eVy++si+eTTUQZU4+8UywSKLia2RattaAPMAcXUjO+3cYOQXLVASdlJtt+8QP dRkfp8SiJemHPXC8BES83pogJPYEGJsKo19l4XFJHPnPy+Dsn3mlJyOfAa8RyWBS 80u5lrvAcr2TJXt9fXgkYs7BOCigxtZoR8flceGRlAZ4p5FPPxQR6NDYb645jtOT MVr3zgfjP6Wh2dt+2p04LG7ENJn8/gEwtXVuXCsPoSCDx9Y0QmyXTJNdV1aB0AhO RkWPlFYwp+zOyOIR+3m1+pqWFpn0eT/HrxpdKa74FA3R2kq4R7dXe4G0kUgXTdqX MLRKhDgdmA==",
    },
    "jacobs": {
        "entity_id": "https://idp2.jacobs-university.de/",
        "url": "https://idp2.jacobs-university.de/idp/profile/SAML2/Unsolicited/SSO",
        "x509cert": "MIIG3jCCBcagAwIBAgIHG1qSwsjboTANBgkqhkiG9w0BAQsFADBsMQswCQYDVQQGEwJERTEnMCUGA1UEChMeSmFjb2JzIFVuaXZlcnNpdHkgQnJlbWVuIGdHbWJIMQ8wDQYDVQQLEwZJUkMtSVQxIzAhBgNVBAMTGkphY29icyBVbml2ZXJzaXR5IENBIC0gRzAxMB4XDTE2MDUxNzEyNTcyM1oXDTE5MDcwOTIzNTkwMFowfDELMAkGA1UEBhMCREUxDzANBgNVBAgMBkJyZW1lbjEPMA0GA1UEBwwGQnJlbWVuMScwJQYDVQQKDB5KYWNvYnMgVW5pdmVyc2l0eSBCcmVtZW4gZ0dtYkgxIjAgBgNVBAMMGWlkcDIuamFjb2JzLXVuaXZlcnNpdHkuZGUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDL6tgpnLfNVLs1RQBhpAu05Bi18xqoii3q8227N8znhy70U0YVHvWmTfAjkCOiae5itP092HemlX+LYE9UWtbiSoAd8ez+Qiv4tzXI47gs0hhAYP+bsp+KaW/kMT4TJf43dq4zPU5VwLOkQzcGOHR1rYOv6aNRBCrBDvwCR8NGmse8gCWoiXY6C73lsR3LDOY4eMe/ujaBz9nlBxGIjVPWV3/mybGjofJQNN4+bGVv3ekBfaSy307hN/uT9wyl5QBUzSq3JMxFweDoNlzP+RswGgJEQIxc4JqIODu/3BLjhrB0hH/jpBDD+xs4+xowc+RD3arYSG1SGItu5jaBcA5Q+UdFQzwLVoasp9NFA3uYcpoEisZzovSCqZ2R7HbyTcePjjLvrv1O25AgjnRglKWEHUP1QugNeSdBxiMCIfjOzcBifjAvlzp0rueAC0203FEnJZAfV4sMKEdPfDhE5BlLHh6Jn5tIS00L1ipaEoRHEKNuZfPq/onMdfmMKSa/4fk1ehlZzZk8n+GfqUiLGfhDpaqqypjeO2uquTHTnSN5Vc/5EnqTz5oSFLEK5vdPf7jdCVgp3rLMwnY0YSAr1dYG9JeXu/hA0xXvJ9qkCUj6//BErjWmCwh8Kxhy/L0HLf1e7uwZqLxAk/Jsf/Bi1vJR4IUFCfgkWZjeXotn9MCSlwIDAQABo4ICczCCAm8wWQYDVR0gBFIwUDARBg8rBgEEAYGtIYIsAQEEAwUwEQYPKwYBBAGBrSGCLAIBBAMBMA8GDSsGAQQBga0hgiwBAQQwDQYLKwYBBAGBrSGCLB4wCAYGZ4EMAQICMAkGA1UdEwQCMAAwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMB0GA1UdDgQWBBSCoU8JU9wjcXItrf+v+k8B7J+IFzAfBgNVHSMEGDAWgBQcq0Ha1JXUnR6CzU19EyU37B+IpzAkBgNVHREEHTAbghlpZHAyLmphY29icy11bml2ZXJzaXR5LmRlMIGVBgNVHR8EgY0wgYowQ6BBoD+GPWh0dHA6Ly9jZHAxLnBjYS5kZm4uZGUvamFjb2JzLXVuaXZlcnNpdHktY2EvcHViL2NybC9jYWNybC5jcmwwQ6BBoD+GPWh0dHA6Ly9jZHAyLnBjYS5kZm4uZGUvamFjb2JzLXVuaXZlcnNpdHktY2EvcHViL2NybC9jYWNybC5jcmwwgeMGCCsGAQUFBwEBBIHWMIHTMDMGCCsGAQUFBzABhidodHRwOi8vb2NzcC5wY2EuZGZuLmRlL09DU1AtU2VydmVyL09DU1AwTQYIKwYBBQUHMAKGQWh0dHA6Ly9jZHAxLnBjYS5kZm4uZGUvamFjb2JzLXVuaXZlcnNpdHktY2EvcHViL2NhY2VydC9jYWNlcnQuY3J0ME0GCCsGAQUFBzAChkFodHRwOi8vY2RwMi5wY2EuZGZuLmRlL2phY29icy11bml2ZXJzaXR5LWNhL3B1Yi9jYWNlcnQvY2FjZXJ0LmNydDANBgkqhkiG9w0BAQsFAAOCAQEAPmDyO/LibHHoAz/suEIg2k4BJ4zmfVvKSfp9tv9Hn5sVPStizYlSDP4Je27DflpZzKdgcLpr9EEpEg5ggXaTAwbCeASDzJEaHkY/y7rXaGOlAz+Mg+1dBR03ApYkuwU939VZH2blXD7to+DNIrsC6+EdkC3MBnvPM/Np0eLCxVjstAmcB3QcnqBYuQ+L+yDRMniaJL13ytPNYhmjyW5Rk3EZ5msGAV4kIfPX0zY+4HxqaoOYLcW0i+EqR4KzoYCTf/7gWbrSUtQNh9JWbwSBBspp3JCOMhhB1XqVD3GKzfA6+e6GcSBFyXnUDl40IQFGIFKarVmoPf6VdmRxDEVO8g=="
    },
}
